### ISSUE TITLE
House emoji on local-only posts

### ISSUE THREAD

**Issue by Taullo** [Taullo/Aerodon#2]
### Steps to reproduce the problem

1. Set post to local only
2. Hit post
3. An eyeball emoji is added to the end of the post
...

### Expected behaviour

No House

### Actual behaviour

House

### Detailed description

The way glitch-soc tells the server to post a toot in local-only mode is to append an eyeball to the end of the post. This behavior is extremely obtuse and confusing.

Updated to a House emoji with b4054ca710d3ea737255e309701a37dc94b5e767

There's two options to fix this:
1) Attempt to find a way to have it only check if the boolean is set to true on the local-only menu option. This would be the most intuitive thing for web users but would provide no solution for app users. Also would require digging into the code more.
2) Hide the emoji on the web app. This would allow mobile users to still write local-only posts however the eyeball would be viewable on apps. 

Leaning toward option one.

Some technical details for later:
1) The eyeball emoji can be edited out of the toot without affecting if the toot is local-only.
2) The local only menu option only adds the eyeball emoji after the hitting "Publish!". Doesn't seem to affect anything else on the backend.

### Specifications

N/A

**Comment by Taullo** [comment]
Changed the emoji from an eyeball to a House with b4054ca710d3ea737255e309701a37dc94b5e767

Some technical updates. The emoji is checked from the backend by:
/mastodon/app/models/status.rb

The emoji is added to the toot in:
_/mastodon/app/javascript/flavours/glitch/actions/compose.js_

It's also referenced in another file for the character counter (not really relevant to aethy):
_/mastodon/app/javascript/flavours/glitch/features/compose/components/compose_form.js_

There's a line in _/mastodon/app/javascript/flavours/glitch/reducers/compose.js_ that implies it's supposed to be replaced with nothing, but it doesn't seem to have any effect??? Unsure what that's about.

Additionally, Local-only should be added to the Post Privacy dropdown as I can't see any reason why someone would want local only and friend only/unlisted. Maybe that can be tackled at the same time?

**Comment by BeebzVivian** [comment]
maybe applying a special class to a house emoji then display none in css. Perhaps a tooltip as to what local only means to the end user, especially one with followers across fedi

**Comment by Taullo** [comment]
Resolved with #95f7518
